name: dailyup_app
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0

  provider: ^6.1.1
  dio: ^5.3.2
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.1.10
  firebase_messaging: ^14.7.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
